name: qt5-core20
base: core20 
version: '20.04'
summary: Qt5 runtime for core20
description: |
  This snap is to be consumed by various Qt apps which uses Qt 5 packages provided from 
  Ubuntu official repository.
  Qt provides C++ classes and QML types for rendering GUI.

grade: stable 
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    run-on: amd64
    
slots: 
  qt5-core20:
    interface: content
    read: 
      - /

parts:
  qt5:
    plugin: nil
    stage-packages:
      # Platform
      - adwaita-icon-theme
      - dmz-cursor-theme
      - fontconfig
      - freeglut3
      - gnome-themes-standard
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - libglib2.0-bin
      - libglu1-mesa
      - libice6
      - libxkbcommon0
      - light-themes
      - locales-all
      - shared-mime-info
      - try: [appmenu-qt5]
      - ttf-ubuntu-font-family
      - xdg-user-dirs

      # Other Desktop integration
      - libfcitx-gclient1
      - libfcitx-utils0
      - fcitx-module-dbus
      - fcitx
      - ibus-gtk3
      - libibus-1.0-5
      - libcanberra-gtk3-module
      - qt5-gtk-platformtheme
      - qt5-gtk2-platformtheme
      - qt5-xdgdesktopportal-platformtheme

      # Qt modules from core20
      - libqt5gui5
      - libqt5sql5-sqlite
      - libqt5svg5 
      - libqt5waylandclient5
      - libqt5webkit5
      - libqt5x11extras5
      - libqt5xml5
      
      # WARNING: optional dependency of ytdlp 
      # do not add it if we are using
      # qt from third party repositories
      # this depends in Qt and QWebkit
      - phantomjs
      
      # Other deps
      - mpv
      - ffmpeg
      - socat
      - wget
      - coreutils
      - pv
      - tar
      - libtag1v5

    override-prime: |

      set -x

      mkdir -p ${SNAPCRAFT_PRIME}/usr/bin/

      cat <<'EOF' > ${SNAPCRAFT_PRIME}/usr/bin/python
      #!/bin/sh
      exec "$SNAP_DESKTOP_RUNTIME/usr/bin/python3.9" "$@"
      EOF

      cat <<'EOF' > ${SNAPCRAFT_PRIME}/usr/bin/python3
      #!/bin/sh
      exec "$SNAP_DESKTOP_RUNTIME/usr/bin/python3.9" "$@"
      EOF

      chmod +x ${SNAPCRAFT_PRIME}/usr/bin/python
      chmod +x ${SNAPCRAFT_PRIME}/usr/bin/python3

      snapcraftctl prime

      # Phantomjs path fix
      mv ${SNAPCRAFT_PRIME}/usr/lib/phantomjs/phantomjs ${SNAPCRAFT_PRIME}/usr/bin/phantomjs

# Python 3.12 build for core20
  python312:
    after:
      - qt5
    plugin: nil
    source: https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz
    source-type: tar
    build-packages:
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - libffi-dev
      - liblzma-dev
      - libncurses5-dev
      - libgdbm-dev
      - libdb-dev
      - uuid-dev
      - tk-dev
      - libuuid1
    override-build: |
      set -eux
      ./configure --prefix=/usr --enable-optimizations --disable-test-modules
      JOBS=$(nproc)
      if [ "$JOBS" -gt 2 ]; then JOBS=2; fi
      make -j$JOBS
      make altinstall DESTDIR=$SNAPCRAFT_PART_INSTALL
    stage:
      - usr
    prime:
      - usr
    override-prime: |
      set -eux
      mkdir -p "${SNAPCRAFT_PRIME}/usr/bin/"

      cat <<'EOF' > ${SNAPCRAFT_PRIME}/usr/bin/python
      #!/bin/sh
      exec "$SNAP_DESKTOP_RUNTIME/usr/bin/python3.12" "$@"
      EOF

      cat <<'EOF' > ${SNAPCRAFT_PRIME}/usr/bin/python3
      #!/bin/sh
      exec "$SNAP_DESKTOP_RUNTIME/usr/bin/python3.12" "$@"
      EOF

      chmod +x ${SNAPCRAFT_PRIME}/usr/bin/python
      chmod +x ${SNAPCRAFT_PRIME}/usr/bin/python3

      snapcraftctl prime
            
  cleanup:
    after:
      - qt5
    plugin: nil
    override-prime: |
      set -eux
      
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
